name: Tic Tac Toe

on:
  issues:
    types: [opened]

jobs:
  tictactoe:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Play Tic Tac Toe
        uses: jasonStoltz/readme-tic-tac-toe@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
